kind: wasmer.io/App.v0
name: vectispay
owner: dipanshukashyap
package: .
enableDatabase: true
env:
  PHPIX_PHP_THREADS: '4'
jobs:
  - name: after_deploy
    trigger: post-deployment
    action:
      execute:
        command: after_deploy
annotations:
  anybuild.run/provider: laravel
  anybuild.run/version: 0.29.0
  wasmer.io/version: 7.4.2
  anybuild.run/config:
    composer_build_script: post-update-cmd
    composer_enable: true
    name: out
    node_build_command: npm run build
    node_install_inputs:
      - package.json
    node_package_manager: npm
    npm_version: '11'
    php_framework: laravel
    php_public_dir: public
    phpix: true
